"""
skills_list.py
--------------
A hand-written list of common Data Analyst / AI skills, grouped by category.

The classical (spaCy) extractor can ONLY find skills that are in this list.
That is the main limitation of the rule-based approach: if a skill is not
written here, it will never be detected.
"""

# Each key is a category name shown in the UI.
# Each value is a list of skill phrases to search for (case does not matter).
SKILLS: dict[str, list[str]] = {
    "Technical Skills": [
        "Python",
        "SQL",
        "R",
        "statistics",
        "machine learning",
        "deep learning",
        "natural language processing",
        "NLP",
        "computer vision",
        "data analysis",
        "data visualization",
        "data cleaning",
        "data wrangling",
        "data modeling",
        "data mining",
        "ETL",
        "A/B testing",
        "hypothesis testing",
        "regression",
        "classification",
        "clustering",
        "time series",
        "forecasting",
        "feature engineering",
        "predictive modeling",
        "neural networks",
        "generative AI",
        "large language models",
        "LLM",
        "prompt engineering",
        "RAG",
        "web scraping",
        "API",
        "data warehousing",
        "cloud computing",
    ],
    "Soft Skills": [
        "communication",
        "problem solving",
        "problem-solving",
        "critical thinking",
        "teamwork",
        "collaboration",
        "stakeholder management",
        "attention to detail",
        "time management",
        "presentation skills",
        "storytelling",
        "leadership",
        "adaptability",
        "curiosity",
        "analytical thinking",
    ],
    "Tools": [
        "Excel",
        "Power BI",
        "Tableau",
        "Looker",
        "Google Sheets",
        "pandas",
        "NumPy",
        "Matplotlib",
        "Seaborn",
        "scikit-learn",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "spaCy",
        "Hugging Face",
        "LangChain",
        "Jupyter",
        "Git",
        "GitHub",
        "Docker",
        "AWS",
        "Azure",
        "GCP",
        "Snowflake",
        "BigQuery",
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "Apache Spark",
        "Airflow",
        "Streamlit",
        "Jira",
    ],
}
